<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net9.0;net8</TargetFrameworks>
        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <!-- Exclude all DLLs from referenced projects by default -->
    <ItemDefinitionGroup>
        <ProjectReference>
            <Private>false</Private>
        </ProjectReference>
    </ItemDefinitionGroup>

    <!-- Jellyfin Core -->
    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
        <PackageReference Include="Jellyfin.Controller" Version="10.11.0" TargetFramework="net9.0" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net8'">
        <PackageReference Include="Jellyfin.Controller" Version="10.10.0" TargetFramework="net8" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
        <!-- Shared dependencies with Jellyfin Core -->
        <PackageReference Include="AsyncKeyedLock" Version="7.1.7" />
        <PackageReference Include="DotNet.Glob" Version="3.1.3" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
        <!-- Own dependencies we need to output with the package -->
        <CommonPackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.10" TargetFramework="net9.0" />
        <CommonPackageReference Include="Microsoft.AspNetCore.SignalR.Client.Core" Version="9.0.10" TargetFramework="net9.0" />
        <CommonPackageReference Include="Microsoft.AspNetCore.Http.Connections.Client" Version="9.0.10" TargetFramework="net9.0" />
        <CommonPackageReference Include="System.Net.ServerSentEvents" Version="9.0.10" TargetFramework="net9.0" />
        <PackageReference Include="@(CommonPackageReference)" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net8'">
        <!-- Shared dependencies with Jellyfin Core -->
        <PackageReference Include="AsyncKeyedLock" Version="6.4.2" />
        <PackageReference Include="DotNet.Glob" Version="3.1.2" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
        <!-- Own dependencies we need to output with the package -->
        <CommonPackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.7" TargetFramework="net8" />
        <CommonPackageReference Include="Microsoft.AspNetCore.SignalR.Client.Core" Version="8.0.7" TargetFramework="net8" />
        <CommonPackageReference Include="Microsoft.AspNetCore.Http.Connections.Client" Version="8.0.7" TargetFramework="net8" />
        <PackageReference Include="@(CommonPackageReference)" />
    </ItemGroup>

    <!-- Code analyzers -->
    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
        <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0" PrivateAssets="All" />
        <PackageReference Include="SerilogAnalyzer" Version="0.15.0" PrivateAssets="All" />
        <PackageReference Include="SmartAnalyzers.MultithreadingAnalyzer" Version="1.1.31" PrivateAssets="All" />
    </ItemGroup>

    <!-- HTML / JS -->
    <ItemGroup>
        <None Remove="Pages\**\*" />
        <EmbeddedResource Include="Pages\**\*" />
    </ItemGroup>

    <Target Name="CopyExtraOutputAssembliesToOutputPath" AfterTargets="Build">
        <GetPublicPackageReferences NuGetPackageRoot="$(NuGetPackageRoot)" PackageReference="@(CommonPackageReference)">
            <Output TaskParameter="Results" ItemName="ExtraOutputAssemblies" />
        </GetPublicPackageReferences>
        <Copy SourceFiles="@(ExtraOutputAssemblies)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
    </Target>

    <UsingTask TaskName="GetPublicPackageReferences" TaskFactory="RoslynCodeTaskFactory" AssemblyName="Microsoft.Build.Tasks.Core">
        <ParameterGroup>
            <NuGetPackageRoot ParameterType="System.String" Required="true" />
            <PackageReference ParameterType="Microsoft.Build.Framework.ITaskItem[]" Required="true" />
            <Results Output="true" ParameterType="Microsoft.Build.Framework.ITaskItem[]" />
        </ParameterGroup>
        <Task>
            <Using Namespace="System.IO" />
            <Using Namespace="System.Linq" />
            <Using Namespace="Microsoft.Build.Framework" />
            <Code Type="Fragment" Language="cs"><![CDATA[
                Results = PackageReference
                    .Select(pkg => new TaskItem(
                        Path.Combine(
                            NuGetPackageRoot,
                            pkg.ItemSpec.ToLowerInvariant(),
                            pkg.GetMetadata("Version"),
                            "lib",
                            pkg.GetMetadata("TargetFramework") == "net8" ? "net8.0" : pkg.GetMetadata("TargetFramework"),
                            pkg.ItemSpec + ".dll"
                        )
                    ))
                    .ToArray();
            ]]></Code>
        </Task>
    </UsingTask>
</Project>
